### ISSUE TITLE
Backend ASP .NET (OWIN): No prepopulated credentials in sample project

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-aspnet-owin-webapi-samples#13]
After downloading the sample project, the app Setings key are not properly populated.

![screenshot_2](https://user-images.githubusercontent.com/15818783/34541353-38682d72-f0ae-11e7-8bfc-ec0f94f8211e.png)

**Comment by jerriep** [comment]
@paulioceano I do not get the same behaviour:

![image](https://user-images.githubusercontent.com/1006420/34658449-d1d2350a-f461-11e7-95c8-d7203bc5afa2.png)

Are you sure you are signed into the Auth0 Dashboard when you do this?

**Comment by paulioceano** [comment]
You are correct, at the moment I have just deleted browser caché/cookies and my credentials has been lost. 

All good.
